---

# Specify the ansible install method
ansible_install_method: 'stable'

# Specify the ansible package name/version.  The value will be used by the
# 'yum', 'apt' and 'pip' modules and must be in a format acceptable to each of
# those modules.
ansible_package_name: 'ansible'

# Specify a nightly package repository url, used when ansible_install_method == 'nightly'
ansible_nightly_repo: 'http://jenkins.testing.ansible.com/ansible_nightlies_QcGXFZKv5VfQHi'

# Specify the PPA that provides 'ansible' stable releases
ansible_ppa: 'ppa:ansible/ansible'

# Indicate the path to the RHUI repository file
redhat_rhui_repo_path: '/etc/yum.repos.d/redhat-rhui.repo'

# Specify RHEL RHUI repositories to enable (used in vars/*.yml).
redhat_rhui_repos: []

# Indicate the path to the subscription-manager repository file
redhat_rhsm_repo_path: '/etc/yum.repos.d/redhat.repo'
redhat_rhsm_cert_path: '/etc/pki/consumer/cert.pem'
redhat_rhsm_conf_path: '/etc/rhsm/rhsm.conf'

# Specify RHEL subscription-manager repositories to enable (used in vars/*.yml).
redhat_rhsm_repos: []

# RPM dependencies needed for the role
rpm_role_dependencies:
    - libselinux-python
    - python-devel
    - autoconf
    - make
    - gcc
    - git
    - yum-utils
    - python-crypto
    - openssl

# DEB dependencies needed for the role
deb_role_dependencies:
    - python-pycurl
    - python-dev
    - autoconf
    - make
    - gcc
    - git
