---
authorized_keys:
    - 'https://github.com/ansible-jenkins.keys'
    - 'https://github.com/chrismeyersfsu.keys'
    - 'https://github.com/jlaska.keys'
    - 'https://github.com/matburt.keys'
    - 'https://github.com/jladdjr.keys'
    - 'https://github.com/jakemcdermott.keys'
    - 'https://github.com/ghjm.keys'
    - 'https://github.com/shanemcd.keys'
    - 'https://github.com/AlanCoding.keys'
    - 'https://github.com/rooftopcellist.keys'
    - 'https://github.com/ryanpetrello.keys'
    - 'https://github.com/wenottingham.keys'
    - 'https://github.com/unlikelyzero.keys'
    - 'https://github.com/one-t.keys'
    - 'https://github.com/kialam.keys'
    - 'https://github.com/benthomasson.keys'
    - 'https://github.com/marshmalien.keys'
    - 'https://github.com/dsesami.keys'
    - 'https://github.com/kdelee.keys'
    - 'https://github.com/Spredzy.keys'
    - 'https://github.com/beeankha.keys'
    - 'https://github.com/elyezer.keys'
    - 'https://github.com/jbradberry.keys'
    - 'https://github.com/AlexSCorey.keys'
    - 'https://github.com/keithjgrant.keys'
    - 'https://github.com/squidboylan.keys'
    - 'https://github.com/appuk.keys'
    - 'https://github.com/rebeccahhh.keys'
    - 'https://github.com/fosterseth.keys'
