---
- hosts: test-runner
  tasks:
    - name: Ensure the artifacts directory exists
      file:
        path: '{{ lookup("env", "PWD") }}/artifacts'
        state: directory
      delegate_to: localhost

    - name: Retrieve junit results
      fetch:
        src: ~/tower-qa/reports/junit/results-final.xml
        dest: '{{ lookup("env", "PWD") }}/artifacts/results.xml'
        flat: true
