---
- hosts: test-runner
  tasks:
    - name: Ensure the artifacts directory exist
      file:
        path: '{{ lookup("env", "PWD") }}/artifacts'
        state: directory
      delegate_to: localhost

    - name: Retrieve artifacts from test runner
      fetch:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        flat: true
      with_items:
        - {src: '~/tower-qa/playbooks/all_tower_sos_reports.tar.gz', dest: '{{ lookup("env", "PWD") }}/artifacts/all_tower_sos_reports.tar.gz'}
        - {src: '~/tower-qa/venv_awx_pip_freeze', dest: '{{ lookup("env", "PWD") }}/artifacts/venv_awx_pip_freeze'}
        - {src: '~/tower-qa/venv_ansible_pip_freeze', dest: '{{ lookup("env", "PWD") }}/artifacts/venv_ansible_pip_freeze'}
