---
# Choose location for ansible package repository (optional)
ansible_nightly_repo: http://nightlies.testing.ansible.com/ansible_nightlies_QcGXFZKv5VfQHi

ansible_git_repo: https://github.com/ansible/ansible.git
ansible_target: devel
