---
# List of RHUI (RH Update Infrastructure) repositories to enable
redhat_rhui_repos:
    - rhel-7-server-rhui-extras-rpms
    - rhel-7-server-rhui-optional-rpms

# List of RHSM (RH Subscription Manager) repositories to enable
redhat_rhsm_repos:
    - rhel-7-server-extras-rpms
    - rhel-7-server-optional-rpms
    # - 'rhel-{{ ansible_distribution_major_version }}-server-extras-rpms'
    # - 'rhel-{{ ansible_distribution_major_version }}-server-optional-rpms'

# RPM dependencies needed for the role
rpm_role_dependencies:
    - libselinux-python
    - python-crypto
    - python-devel
    - autoconf
    - make
    - gcc
    - git
    - yum-utils
    - openssl
    - nss
    - curl
