---
- name: Copy inspircd.conf
  become: true
  become_user: "{{ inspircd_user }}"
  template:
    src: inspircd.conf.j2
    dest: "{{ inspircd_conf_dir }}/inspircd.conf"
    force: true
    backup: true
  notify:
    - Restart inspircd

- name: Copy modules.conf
  become: true
  become_user: "{{ inspircd_user }}"
  template:
    src: modules.conf.j2
    dest: "{{ inspircd_conf_dir }}/modules.conf"
    force: true
    backup: true
  notify:
    - Restart inspircd

- name: Copy motd.txt
  become: true
  become_user: "{{ inspircd_user }}"
  template:
    src: motd.txt.j2
    dest: "{{ inspircd_conf_dir }}/motd.txt"
    force: true
    backup: true
  notify:
    - Restart inspircd

- name: Copy opers.conf
  become: true
  become_user: "{{ inspircd_user }}"
  template:
    src: opers.conf.j2
    dest: "{{ inspircd_conf_dir }}/opers.conf"
  notify:
    - Restart inspircd

- name: Copy rules.txt
  become: true
  become_user: "{{ inspircd_user }}"
  template:
    src: rules.txt.j2
    dest: "{{ inspircd_conf_dir }}/rules.txt"
  notify:
    - Restart inspircd
