---
- name: detect if PyYAML rpm is installed
  command: rpm -q PyYAML
  args:
    warn: false
  changed_when: false
  ignore_errors: true
  register: is_pyyaml_pkg_installed
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: detect pip installed packages
  shell: pip list | awk '{print $1}'
  changed_when: false
  ignore_errors: true
  register: installed_pips

# The following will only run if pip modules were detected in the previous task
- name: remove unpackaged PyYAML library
  pip:
    state: absent
    name: PyYAML
  when: installed_pips is success and 'PyYAML' in installed_pips.stdout and is_pyyaml_pkg_installed is failed
