---
- name: create instance(s)
  hosts: local
  roles:
    - role: create_ec2
    - role: save_inventory
      my_inventory_file: '{{inventory_dir}}/inventory.cluster'

- name: 'Add authorized keys on non-installer instances'
  hosts: 'tower:instance_group_*:database:isolated_group_*:haproxy:managed_hosts:secondary:!cluster_installer'
  roles:
    - role: auth_keys

- name: 'Group hosts by distribution_major_version'
  hosts: 'tower,instance_group_*,primary,secondary'
  tasks:
   - name: group hosts by distribution_major_version
     action: group_by key="{{ansible_distribution}}-{{ansible_distribution_major_version}}"

- name: 'Configure cluster ssh keys'
  hosts: 'tower:instance_group_*:isolated_group_*:primary:secondary:database'
  roles:
    - { role: cluster_key_config, install_group: "{{ 'cluster_installer' if 'cluster_installer' in groups else 'primary' }}" }

- name: 'Install cluster tower on installer instance'
  hosts: 'cluster_installer,primary'
  gather_facts: no
  become: true
  become_method: sudo
  roles:
    - role: awx_setup

- name: 'install and configure haproxy'
  hosts: 'haproxy'
  roles:
    - role: haproxy
  gather_facts: no
  become: true
  become_method: sudo
