---
- name: Deploy cloud hosts
  hosts: local
  tasks:
    - include_role:
        name: create_ec2
      when: not awx_upgrade | default(false) | bool

    - include_role:
        name: save_inventory
      vars:
        my_inventory_file: '{{inventory_dir}}/inventory.log'
      when: not awx_upgrade | default(false) | bool

- name: 'Add authorized keys on database'
  hosts: 'database'
  roles:
    - role: auth_keys

- name: 'Dynamically create host groups'
  hosts: 'tower'
  tasks:
    - name: group hosts by distribution_major_version
      group_by:
        key: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"
      changed_when: false

- name: Generate TLS certificates when specified
  hosts: tower
  tasks:
    - name: Run TLS certificates generation playbooks
      include_role:
        name: generate_tls_certificates
      when: awx_use_tls | default(false) | bool

- name: Enable FIPS for tower nodes
  hosts: tower
  tasks:
    - name: Run FIPS Role
      include_role:
        name: fips
      when: awx_use_fips | default(false) | bool and not awx_upgrade | default(false) | bool

- name: 'Install Tower'
  hosts: 'tower'
  gather_facts: false
  become: true
  become_method: sudo
  environment:
    PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
  roles:
    - {role: awx_setup}

- name: Install specific version of ansible-runner (if applies)
  hosts: tower
  gather_facts: false
  become: true
  tasks:
    - include_role:
        name: ansible_runner
      when: awx_ansible_runner_url is defined and awx_ansible_runner_url != ''

- name: Remove IPV4
  hosts: tower
  tasks:
    - include_role:
        name: ipv6
      when: awx_ipv6_deployment | default(false) | bool

    - name: Save ipv6 to name resolution locally
      become: true
      delegate_to: localhost
      blockinfile:
        path: /etc/hosts
        block: |
          {{ hostvars[item]["ansible_default_ipv6"]["address"] }} {{ hostvars[item]["inventory_hostname"] }}
      with_items: '{{ groups["tower"] }}'
      when: awx_ipv6_deployment | default(false) | bool
