---
- name: Generate the /etc/resolv.conf file
  become: true
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Generate the /etc/hosts file
  become: true
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Remove ipv4 address from device
  become: true
  command: ip addr del '{{ ansible_default_ipv4.address }}' broadcast '{{ ansible_default_ipv4.gateway }}' dev '{{ ansible_default_ipv4.interface }}'
  ignore_errors: true
