---
# Whether to upgrade an existing awx installation
awx_upgrade: false

# Whether to run an HA installation
cluster_install: false

# Whether to run any package-related OS preparations
out_of_box_os: false

# Choose location for ansible-tower package repository
aw_repo_url: 'http://nightlies.testing.ansible.com/ansible-tower_nightlies_m8u16fz56qr6q7/devel'
# aw_repo_url: 'http://releases.ansible.com/ansible-tower'

# Choose location for awx-setup
awx_setup_path: /setup/ansible-tower-setup-latest.tar.gz
# awx_setup_path: /setup/ansible-tower-setup-2.3.0.tar.gz
# awx_setup_path: /setup/ansible-tower-setup-2.2.2.tar.gz
# awx_setup_path: /setup/ansible-tower-setup-2.1.6.tar.gz

# Defaults for postgres variables (comes from ansible-tower/setup/inventory)
pg_database: 'awx'
pg_username: 'awx'
pg_password: 'password'

# Defaults for rabbitmq
rabbitmq_port: 5672
rabbitmq_vhost: 'tower'
rabbitmq_username: 'tower'
rabbitmq_password: 'tower'
rabbitmq_use_long_name: '{{ cluster_install }}'
rabbitmq_cookie: 'cookiemonster'
rabbitmq_enable_manager: '{{ cluster_install }}'

# Optionally customize the default awx passwords
# admin_password: fo0m4nchU
# pg_password: 9CJCSUtePvE
# rabbitmq_password: 9CJCSUtePvE

# Default minimum var space (disabled with '0'):
minimum_var_space: 0
disable_ssl: false

isolated_key_generation: true
